apiVersion: v1
kind: ConfigMap
metadata:
  name: twitter-clone-config
  namespace: twitter-clone
data:
  application.yml: |
    spring:
      application:
        name: twitter-clone
      
      datasource:
        url: jdbc:h2:mem:twitterdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password: 
        
      h2:
        console:
          enabled: true
          path: /h2-console
          
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: create-drop
        show-sql: false
        properties:
          hibernate:
            format_sql: true
            
      jackson:
        serialization:
          write-dates-as-timestamps: false
        time-zone: UTC

    server:
      port: 8080
      servlet:
        context-path: /api

    logging:
      level:
        com.twitter: INFO
        org.springframework.security: WARN
        org.hibernate.SQL: WARN
        
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: always

    app:
      jwt:
        secret: ${JWT_SECRET:mySecretKey}
        expiration: 86400000